### ISSUE TITLE
Sign up returns error

### ISSUE THREAD

**Issue by msolomonTMG** [msolomonTMG/jira-comment-slack-notification#14]
Sometimes, when a user clicks a signup link from Slack, they are presented with an error rather than the Jira OAuth screen.

**Steps to Reproduce**

1. Message the slackbot with "signup" with a slack user who is not yet signed up
2. Click the signup link that is returned
**Expected:** user is presented with Jira OAuth screen
**Actual:** user is presented with an error message

**Observations:** 
-  mongodb shows the user signed up with their slack username but not their Jira username
- if the user is deleted from the mongodb and tries signing up again, signup is successful
- this signup issue appears to be related to the amount of time it takes heroku to wake up after going to sleep because signups that occur when heroku is awake tend to be successful

**Comment by edahlseng** [comment]
I've seen a similar error before as well, without using Heroku. It may be related to an uncaught promise, if I remember right. In any case, I'll check it out more fully.

**Comment by jholmstadt** [comment]
I spent a little time trying to figure out a fix for this, and came up with something that seems to work fine for our deployment: https://github.com/teamlakana/jira-comment-slack-notification/commit/ced3e716838fcd35dc84454dd6a6b76d32bb9735

I don't know much about nodeJS, however it seemed to me that if the user exists in the DB, then all that happens is that it logs to the console, and eventually the request times out because there is no response. Instead, I made it respond with a redirect to the /auth URL so that the user can complete the JIRA authorization. That could lead to multiple JIRA auth attempts, but that doesn't seem to harm anything.

**Comment by agfa555** [comment]
Hi, first of all thank you for this.
We find this idea super useful but I'm stuck in this same step.

Everything was configured correctly but when trying to signup I get the error message.
Also, if I try to signup again I get the message "You're already signed up!" and a link: "Click here to adjust your settings"
If I click that I get to a screen that says forbidden.

I also tried @jholmstadt fork with the same result. :'(

Any help would be greatly appreciated.
