### ISSUE TITLE
Is jira server supported

### ISSUE THREAD

**Issue by leevs** [msolomonTMG/jira-comment-slack-notification#15]
Hi, we would like to know if you also support the jira server setup (meaning installation "on-premise").
The README is unclear on this one that is would actually be possible.

Could you let us know if it's possible and adjust your README to know what the outcome is as this might be a recurring question

**Comment by msolomonTMG** [comment]
I have never used a Jira Server instance before but if there is truly no difference in the Jira application, then these steps should work just fine. @leevs please let us know if these steps work for your Jira Server instance so that we can update the README accordingly.

One possible issue that comes to mind about Jira Server instances is if you have some sort of VPN or Network configuration that prevents your Jira application from being reached by the internet. If that is the case, I would think Heroku would not be able to communicate with Jira and that could cause the integration to fail.
